### ISSUE TITLE
Node.js v20 needs updating

### ISSUE THREAD

**Issue by EmHain8** [qgisau/qgis-au.github.io#5]
I currently can't push out any content. I tried to work out where to deploy it but couldn't. Please let me know how this is done. 

build
`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/configure-pages@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.`

**Comment by EmHain8** [comment]
Ok so cannot push any content out until this is fixed.

**Comment by NathanW2** [comment]
I will look tomorrow.

**Comment by EmHain8** [comment]
any luck here? do we update [Hugo](https://github.com/gohugoio/hugo/releases) I can't get content out.

**Comment by NathanW2** [comment]
@EmHain8 was invalid value in the date field:


That is the build error
https://github.com/qgisau/qgis-au.github.io/actions/runs/8562381395/job/23588278998

and this is the fix:

https://github.com/qgisau/qgis-au.github.io/commit/b4bf545c5d410bb7e7c2340b9f1c2055ff52d633#diff-435ef7356fe9d5cc98050fd9d3a6151ab05ce1508f8ee21a77e7e185bce8057dR3

**Comment by EmHain8** [comment]
thanks

**Comment by EmHain8** [comment]
seriously - such a simple thing. I cannot!! Goodness!!
